sudo: required
services:
  - docker

before_install:
  - docker build -t yu8861213/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yu8861213/react-test npm test

after_success:
  - docker build -t yu8861213/multi-client ./client
  - docker build -t yu8861213/multi-nginx ./nginx
  - docker build -t yu8861213/multi-server ./server
  - docker build -t yu8861213/multi-worker ./worker
  # log in th the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push yu8861213/multi-client
  - docker push yu8861213/multi-nginx
  - docker push yu8861213/multi-server
  - docker push yu8861213/multi-worker